BloodDonorApp.Web/Models/ErrorViewModel.cs
using System;

namespace BloodDonorApp.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BloodDonorApp.Web/Controllers/AccountController.cs
using BloodDonorApp.Application.Interfaces;
using BloodDonorApp.Application.ViewModel;
using BloodDonorApp.DataLayer.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BloodDonorApp.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly IBloodDonorService _bloodDonorService;

        public AccountController(IBloodDonorService bloodDonorService)
        {
            _bloodDonorService = bloodDonorService;
        }
        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignUp(CreateSignUpUserModel signUpUser)
        {
            var result = await _bloodDonorService.CreateAsync(signUpUser);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            ModelState.Clear();
            return View();
        }
        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignIn(CreateSignInUserModel signInUser)
        {
            var result = await _bloodDonorService.PasswordSignInAsync(signInUser);
           if(result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public async Task<IActionResult> SignOut()
        {
            await _bloodDonorService.SignOutAsync();
            return RedirectToAction("Index","Home");
        }

        [HttpGet]
        public async Task<IActionResult> GetDonorList()
        {
            var donors = await _bloodDonorService.GetDonorListAsync();
            return View(donors);
        }
        [HttpGet]
        public IActionResult ChangePassWord()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassWord(ChangePasswordViewModel newpass)
        {
            var result =await _bloodDonorService.ChangePasswordAsync(newpass.CurrentPassword, newpass.NewPassword);
            await _bloodDonorService.SignOutAsync();
            return RedirectToAction("SignIn");
        }
    }
}

BloodDonorApp.Web/Controllers/AuthorizationController.cs
using BloodDonorApp.Application.Interfaces;
using BloodDonorApp.Application.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BloodDonorApp.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AuthorizationController : Controller
    {
        private readonly IBloodDonorService _bloodDonorService;

        public AuthorizationController(IBloodDonorService bloodDonorService)
        {
            _bloodDonorService = bloodDonorService;
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel role)
        {
            var result =await _bloodDonorService.CreateRoleAsync(role);
            if(!result.Succeeded)
            {
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("",error.Description);
                }
                ModelState.Clear();
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> RoleList()
        {
            var result = await _bloodDonorService.GetRoleListAsync();
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> EditUserInRole(string id)
        {
            var rs =await _bloodDonorService.EditUserInRole(id);
            return View(rs);
        }
        [HttpPost]
        public async Task<IActionResult> EditUserInRole(string id, List<EditUserInRoleViewModel> model)
        {
            await _bloodDonorService.AssignUserInRoleAsync(id, model);

            return RedirectToAction("RoleList");
        }
    }
}

BloodDonorApp.Web/Controllers/HomeController.cs
using BloodDonorApp.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BloodDonorApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BloodDonorApp.Web/Views/Authorization/CreateRole.cshtml
@model BloodDonorApp.Application.ViewModel.CreateRoleViewModel

@{
    ViewData["Title"] = "CreateRole";
}

<h1>CreateRole</h1>

<h4>CreateRoleViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRole">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BloodDonorApp.Web/Views/Authorization/EditUserInRole.cshtml
@model IList<BloodDonorApp.Application.ViewModel.EditUserInRoleViewModel>
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor _httpContext;

@{
    ViewData["Title"] = "EditUserInRole";
}

<div class="row">
    <div class="col-lg-6 offset-3">

        <form method="post">
            <div class="card">
                <div class="card-header">
                    <h2>Add or Remove User To Role</h2>
                </div>
                <div class="card-body">
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        @if (_httpContext.HttpContext.User.Identity.Name == Model[i].UserName)
                        {
                            <input asp-for="@Model[i].IsSelected" type="hidden" class="form-check-input">

                        }
                        else
                        {
                            <input asp-for="@Model[i].IsSelected" class="form-check-input">
                            <label class="form-check-label" asp-for="@Model[i].IsSelected">@Model[i].UserName</label><br>
                        }
                }
                </div>
                <div class="card-footer">
                    <input type="submit" class="btn btn-primary" value="Update">
                    <a asp-action="getRolelist" asp-controller="Authorization" class="btn btn-primary">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

BloodDonorApp.Web/Views/Authorization/RoleList.cshtml
@model IEnumerable<BloodDonorApp.Application.ViewModel.CreateRoleViewModel>

@{
    ViewData["Title"] = "RoleList";
}

<h1>RoleList</h1>

<p>
    <a asp-action="CreateRole">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.RoleName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) 
{
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id }) |
                @Html.ActionLink("Add or Remove user", "EditUserInRole", new {  id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>

BloodDonorApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BloodDonorApp.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using BloodDonorApp.Entites.Model
@inject SignInManager<ApplicationUser> _signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BloodDonorApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BloodDonorApp.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="GetDonorList">Donor List</a>
                        </li>
                        @if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="RoleList">Manage Roles</a>
                            </li>
                        }
                        <li class="nav-item">
                            <partial name="_navbar" />
                        </li>

                    </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - BloodDonorApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>

BloodDonorApp.Web/Views/Shared/_navbar.cshtml
@using Microsoft.AspNetCore.Identity
@using BloodDonorApp.Entites.Model
@inject SignInManager<ApplicationUser> _signInManager

@if(User.Identity.IsAuthenticated)
{
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hello @User.Identity.Name
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" asp-action="Signout" asp-controller="Account">Signout</a>
            <a class="dropdown-item" asp-action="ChangePassword" asp-controller="Account">Change password</a>
        </div>
    </li>
}
else
{

    <li class="nav-item">
        <a class="btn btn-outline-primary" asp-controller="Account" asp-action="SignIn" asp-route-returnUrl="@Context.Request.Path">SignIn</a>
        <a class="btn btn-primary" asp-controller="Account" asp-action="Signup">Register</a>
    </li>
}